### ISSUE TITLE
bizzare factor levels of civil variable

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_geo-mortality#12]
Hi @jriou 

Could you plz check what might be the issue with incorrect levels of factor variable `civil`?
I tried to include into dataset and run into some unexplainable behaviour.

Thaaanks 🙏

**Comment by jriou** [comment]
I can't read this px file, I keep having an obscure error about C stack usage being too close to the limit. I didn't find a solution yet.

**Comment by RPanczak** [comment]
Resolved in new data - civil status is not availalbe.
