### ISSUE TITLE
dealing with very small grid cells 

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/ISPM_geo-mortality#49]
when grid is cropped using swisstopo [boundaries ](https://www.swisstopo.admin.ch/de/geodata/landscape/boundaries3d.html) of municipalities it occasionally creates very small cells  

we need some clever way to get rid of those?

![image](https://user-images.githubusercontent.com/31648642/147944564-c9310f8d-308e-424e-9f28-6902ab148938.png)

**Comment by gkonstantinoudis** [comment]
what we need to have in general is the grid and then to do smth clever to assign from the boundaries to the grid. What is normally done in such circumstances is to calculate weights based on the areas and assign the population number to the grid cells based on the areas. We can do the same for the number of cases too.

**Comment by RPanczak** [comment]
Ok, thanks. I understand now. 
But then what do you do with these tiny grid cells? Look at the area calculation - that is square meters!
Sure there is probably zero chance there will be a building located there. So anything assigned to it would be zero.
But wouldn't that trip the models in any way?

**Comment by RPanczak** [comment]
@gkonstantinoudis one more issue here

I'm working on generating some sample data; below is example of smallest community in 🇨🇭 

After integrating community boundaries into the grid I'm left with small so called 'sliver' polygons

![image](https://user-images.githubusercontent.com/31648642/149807767-e5545ab4-0b0d-4452-80d5-f49c18f37072.png)

At the moment two slivers in yellow are both correctly assigned to municipality above them.  They will of course most likely have zero pops and zero deaths assigned to them. 

They do however have the same gird cell ID because they were derived from the same regular grid cell below them. 

So any operation that aggregates data 'by ID' will assign these values to both of this small polygons. 

Does it matter to you at later, analytical stage what ID they have?
